# Generated by Django 3.1.4 on 2021-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
