# Generated by Django 3.1.4 on 2021-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='branch',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='key',
            new_name='subcode',
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
